version: '3'
services:
    mongodb:
        image: mongo
        container_name: mongodb
        restart: unless-stopped
        environment:
            - MONGO_INITDB_ROOT_USERNAME={username}
            - MONGO_INITDB_ROOT_PASSWORD={password}
        volumes:
            - ./database:/data/db
            # - mongodb-data:/data/db
        # command: [--auth]
        networks:
            - mongodb_network
        ports:
            - '27017:27017'
    mongo-express:
        image: mongo-express
        container_name: mongo-express
        restart: unless-stopped
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_ADMINUSERNAME={db username}
            - ME_CONFIG_MONGODB_ADMINPASSWORD={db password}
            - ME_CONFIG_BASICAUTH_USERNAME={express username}
            - ME_CONFIG_BASICAUTH_PASSWORD={express password}
        volumes:
            - ./database
            # - mongodb-data
        depends_on:
            - mongodb
        networks:
            - mongodb_network
        ports:
            - '8081:8081'

# volumes:
#     mongodb-data:
#         name: mongodb-data-name
networks:
    mongodb_network:
        name: mongodb_network

